camunda.bpm.admin-user:
  id: admin
  password: admin

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    password: admin
    username: admin
    url: jdbc:h2:mem:hack2react
  jpa:
    hibernate:
      ddl-auto: create